# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import form.util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('adm_no', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phno', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=form.util.RandomFileName('images'), verbose_name='Images')),
            ],
        ),
    ]
