# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20190304_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='adm_no',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
