# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import form.util


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_auto_20190305_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=form.util.RandomFileName('submission_files/submission_{id}')),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=form.util.RandomFileName('submission_files/submission_{id}')),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=form.util.RandomFileName('submission_files/submission_{id}')),
        ),
    ]
